### ISSUE TITLE
Upgrade MRT

### ISSUE THREAD

**Issue by kaveon14** [MetLifeLegalPlans/wui#92]
Upgrade MRT to V2 https://www.material-react-table.com/

**Comment by kaveon14** [comment]
@kelarcrisp Unless I'm not understanding correctly, I think this ticket it already done:

https://github.com/MetLifeLegalPlans/wui/blob/9c3439fa91eaa810e7e30fadf9f29e2c24418498/package.json#L68

**Comment by kelarcrisp** [comment]
@kaveon14 closing this issue then
